config/routes.rb
EUUCRE::Application.routes.draw do
  get "families/index"

  get "families/show"

  get "families/edit"

  get "families/delete"

  get "home/index"

  resources :families do
    resources :people
  end
  resources :groups
  resources :teachers
  resources :assistants
  resources :students

  root :to => 'home#index'

end

app/models/assistant.rb
class Assistant < ActiveRecord::Base
  belongs_to :person
  belongs_to :group
end

app/models/family.rb
class Family < ActiveRecord::Base
      has_many :people, :dependent => :destroy
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :teachers
  has_many :assistants
  has_many :students
end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :first_name, :last_name, :family_role, :presence => true
  belongs_to :family
  has_many :assistants
  has_many :teachers
  has_one :student
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :person
  belongs_to :group
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  belongs_to :person
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  http_basic_authenticate_with :name=> "sarahd", :password => "euucdb", :except => :index
  before_filter :find_family, :only => [:show,
                                        :edit,
                                        :update,
                                        :destroy]
  def index
    @families = Family.order("name ASC")
    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @families }
    end
  end

  def new
    @family = Family.new
    respond_to do |format|
      format.html  # new.html.erb
      format.json  { render :json => @family }
    end
  end

  def create
    @family = Family.new(params[:family])
    respond_to do |format|
      if @family.save
        format.html  { redirect_to(@family,
                      :notice => 'Family was successfully created.') }
        format.json  { render :json => @family,
                      :status => :created, :location => @family }
      else
        format.html  { render :action => "new" }
        format.json  { render :json => @family.errors,
                      :status => :unprocessable_entity }
      end
    end
  end

  def show
    respond_to do |format|
      format.html  # show.html.erb
      format.json  { render :json => @family }
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @family.update_attributes(params[:family])
        format.html  { redirect_to(@family,
                      :notice => 'Family was successfully updated.') }
        format.json  { render :json => {}, :status => :ok }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @family.errors,
                      :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @family.destroy
    respond_to do |format|
      format.html { redirect_to families_url }
      format.json { head :ok }
    end
  end

  private
    def find_family
      @family = Family.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      flash[:alert] = "That family isn't found."
      redirect_to families_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  http_basic_authenticate_with :name => "sarahd", :password => "euucdb", :only => :destroy
  before_filter :find_family
  before_filter :find_person, :only => [:destroy, :edit, :update]

  def new
    @person = @family.people.build
  end

  def create
    begin
      @person = @family.people.create!(params[:person])
    rescue ActiveRecord::RecordInvalid
      flash[:alert] = "Didn't create the person"
      redirect_to new_family_person_path(@family)
    else
      flash[:notice] = "Person created"
      redirect_to family_path(@family)
    end
  end

  def destroy
    @person.destroy
    redirect_to family_path(@family)
  end

  def edit

  end

  def update
    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html  { redirect_to(@family,
                      :notice => 'Family was successfully updated.') }
        format.json  { render :json => {}, :status => :ok }
      else
        format.html  { render :action => "edit" }
        format.json  { render :json => @person.errors,
                      :status => :unprocessable_entity }
      end
    end
  end

  private
    def find_person
      begin
        @person = @family.people.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        flash[:alert] = "Didn't find the person"
      end
      redirect_to family_path(@family)
    end

  private
    def find_family
      @family = Family.find(params[:family_id])
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/families/_form.html.erb
<%= form_for(@family) do |f| %>
  <% if @family.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@family.errors.count, "error") %> prohibited this family from being saved:</h2>
    <ul>
    <% @family.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/families/edit.html.erb
<h1>Editing family</h1>
 
<%= render 'form' %>
 
<%= link_to 'Show', @family %> |
<%= link_to 'Back', families_path %>

app/views/families/index.html.erb
<h1>Families</h1>
<table>
  <tr><th>Name</th></tr>
  <% @families.each do |family| %>
    <tr><td><%= family.name %></td>
        <td><%= link_to 'Show', family %></td>
        <td><%= link_to 'Edit', edit_family_path(family) %></td>
        <td><%= link_to 'Destroy',  family, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<br/>

<%= link_to 'New Family', new_family_path %>

app/views/families/new.html.erb
<h1>Create a new family</h1>

<%= render 'form' %>
 
<%= link_to 'Back', families_path %>

app/views/families/show.html.erb
<h1>Family</h1>

<p class="notice"><%= notice %></p>
 
<p>
  <b>Name:</b>
  <%= @family.name %> 
</p>
<%= link_to 'New Person', new_family_person_path(@family) %>  |
<%= link_to 'Edit Family', edit_family_path(@family) %> |
<%= link_to 'Back to All Families', families_path %>
<br />
<br />

<h2>People</h2>
<% @family.people.each do |person| %>
<div class="<%= person.family_role%>">
  <%= person.first_name %> <%= person.last_name %><br />
  <span class="adult_show">
    <%= person.address %><br />
    <%= person.city %>, <%= person.state %> <%= person.zip_code %><br />
    H: <%= person.home_phone %> C: <%= person.cell_phone %>
    W: <%= person.work_phone %> E: <%= person.email %>
    Preferred: <%= person.preferred_contact_method %><br />
  </span>
  <span class="child_show">
    Gender Identification: <%= person.gender_identification %> <br />
    Birthdate: <%= person.birthdate %> <br />
    Active: <%= person.active %> <br />
  </span>
  Public note: <%= person.public_note %><br />
  <span class="admin_show">
    Admin note: <%= person.admin_note %> <br />
  </span>
  Family Role: <%= person.family_role %> <br />
</div>
  <%= link_to 'Edit Person', edit_family_person_path(@family, person) %>

  <%= link_to 'Destroy Person', [person.family, person],
      :confirm => 'Are you sure?',
      :method => :delete %>   <br/><br/>
<% end %>

app/views/home/index.html.erb
<h1>EUUC RE db</h1>

<p><%= link_to 'See families.', families_path %></p>
<p>Set up classes.</p>
<p>Associate teachers with classes.</p>
<p>Associate assistants with classes.</p>
<p>Associate children with classes.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EUUCRE</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |key, value| %>
  <div class="flash" id='<%= key %>'>
    <%= value %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for([@family, @person]) do |f| %>
  <div class="field">
    <%= f.label :family_role %>: <%= radio_button("person", "family_role", "Adult 1", {:class =>"Adult"}) %> Adult 1
    <%= radio_button("person", "family_role", "Adult 2", {:class => 'Adult'}) %> Adult 2
    <%= radio_button("person", "family_role", "Child", {:class => 'Child'}) %> Child
  </div>
  <span class="show">
  <div class="field">
    <%= f.label :first_name %>: <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>: <%= f.text_field :last_name %>
  </div>
  <div class="field adult_show">
    <%= f.label :address %>: <%= f.text_field :address %>
  </div>
  <div class="field adult_show">
    <%= f.label :city %>: <%= f.text_field :city %>
  </div>
  <div class="field adult_show">
    <%= f.label :state %>: <%= f.text_field :state, :value => "WA" %>
  </div>
  <div class="field adult_show">
    <%= f.label :zip_code %>: <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :home_phone %>: <%= f.text_field :home_phone %>
  </div>
  <div class="field">
    <%= f.label :cell_phone %>: <%= f.text_field :cell_phone %>
  </div>
  <div class="field adult_show">
    <%= f.label :work_phone %>: <%= f.text_field :work_phone %>
  </div>
  <div class="field">
    <%= f.label :email %>: <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :preferred_contact_method %>: <%= radio_button("person", "preferred_contact_method", "home") %> Home
    <%= radio_button("person", "preferred_contact_method", "cell") %> Cell
    <%= radio_button("person", "preferred_contact_method", "email") %> Email
    <span class="adult_show"><%= radio_button("person", "preferred_contact_method", "work") %> Work</span>
  </div>
  <div class="field child_show">
    <%= f.label :gender_identification %>: <%= radio_button("person", "gender_identification", "M") %> M  <%= radio_button("person", "gender_identification", "F") %> F  <%= radio_button("person", "gender_identification", "O") %> O
  </div>
  <div class="field child_show">
    <%= f.label :birthdate %>: <%= date_select :person, :birthdate, :start_year => 1930 %>
  </div>
  <div class="field child_show">
    <%= f.label :active %>: <%= check_box("person", "active") %>
  </div>
  <div class="field">
    <%= f.label :public_note %>: <%= f.text_area :public_note %>
  </div>
  <div class="field admin_show">
    <%= f.label :admin_note %>: <%= f.text_area :admin_note %>
  </div>
  </span>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/_person.html.erb
<%= person.first_name %> <%= person.last_name %><br />
<%= person.address %><br />
<%= person.city %>, <%= person.state %> <%= person.zip_code %><br />
H: <%= person.home_phone %> C: <%= person.cell_phone %> W: <%= person.work_phone %> E: <%= person.email %> Preferred <%= person.preferred_contact_method %><br />
Gender Identification: <%= person.gender_identification %> Birthdate: <%= person.birthdate %> Active: <%= person.active %>
Public note: <%= person.public_note %>
Admin note: <%= person.admin_note %>
Family Role: <%= person.family_role %>

<%= link_to 'Edit Person', edit_family_person_path(@family, @person) %>

<%= link_to 'Destroy Person', [person.family, person],
    :confirm => 'Are you sure?',
    :method => :delete %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>
 |
<%= link_to 'Back', family_path %>

app/views/people/new.html.erb
<h2>Add a person to the <%= @family.name %> family:</h2>

<%= render "people/form" %>

<%= link_to 'Return to family', @family %>